# Generated by Django 3.1.6 on 2021-02-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('availble', 'anailble'), ('rantal', 'rental'), ('sold', 'sold')], max_length=50, null=True),
        ),
    ]
